planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
  PRMstar:
    type: geometric::PRMstar

right_arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  longest_valid_segment_fraction: 0.01

left_arm:
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
  longest_valid_segment_fraction: 0.01

dual_arms:
  planner_configs:
    - RRTConnect
    - PRMstar
  longest_valid_segment_fraction: 0.01

head:
  planner_configs:
    - RRTConnect
  longest_valid_segment_fraction: 0.02
